project:
  type: website
  output-dir: docs
  resources: 
    - cv.pdf

resources:
  - CNAME

website:
  title: "Jiho Kim"
  favicon: favicon.ico
  google-analytics: G-HWSQBSH4R7
  open-graph: true
  twitter-card: true
  site-url: https://jihokim.dev
  repo-url: https://github.com/nghtctrl/nghtctrl.github.io
  issue-url: https://github.com/nghtctrl/nghtctrl.github.io/issues/new/choose
  repo-actions: [source, issue]
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  navbar:
    search: true
    left:
      - text: "Publications"
        aria-label: "Publications"
        href: pubs
      - text: "Projects"
        aria-label: "Projects"
        href: proj
      - text: "Blog"
        aria-label: "Blog"
        href: blog
    right:
      - icon: linkedin
        text: LinkedIn
        aria-label: "LinkedIn"
        href: https://www.linkedin.com/in/jiho-kim-128aa0199
      - icon: mastodon
        text: Mastodon
        aria-label: "Mastodon"
        href: https://hci.social/@jihokim
      - text: "{{< iconify simple-icons bluesky>}} Bluesky"
        aria-label: "Bluesky"
        href: https://bsky.app/profile/jihokim.dev
  
format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
